apiVersion: v1
data:
  nginx.conf: |
    events {}

    http {
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;  # Resolve DNS
      server {
        listen 8081;

        location / {
          proxy_pass http://frontend-service:3000; # inside k8s
    #       proxy_pass http://host.docker.internal:3000; # outside dev env
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $http_host;
        }

        location /api/users {
          rewrite ^/api/users/?(.*)$ /$1 break;
          proxy_pass http://user-service:3001;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $http_host;  # Set X-Forwarded-Host
        }

        location /api/tasks {
          rewrite ^/api/tasks/?(.*)$ /$1 break;
          proxy_pass http://task-service:3002;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $http_host;  # Set X-Forwarded-Host
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: api-gateway
  name: api-gateway-cm0
