apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: frontend-service
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: frontend-service
    spec:
      containers:
        - env:
            - name: SITE_URL
              value: http://api-gateway:8081
          image: energizer91/todo-assignment-frontend-service
          name: frontend-service
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: # The resources field specifying requests and limits
            requests:
              cpu: "100m"                 # Minimum CPU to be allocated
              memory: "256Mi"             # Minimum memory to be allocated
            limits:
              cpu: "500m"                 # Maximum CPU that the container can use
              memory: "512Mi"             # Maximum memory that the container can use
      restartPolicy: Always
