apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: MONGO_URI
              value: mongodb://mongodb:27017/todo-app
            - name: PORT
              value: "3001"
          image: energizer91/todo-assignment-user-service
          name: user-service
          ports:
            - containerPort: 3001
              protocol: TCP
          resources: # The resources field specifying requests and limits
            requests:
              cpu: "100m"                 # Minimum CPU to be allocated
              memory: "256Mi"             # Minimum memory to be allocated
            limits:
              cpu: "500m"                 # Maximum CPU that the container can use
              memory: "512Mi"             # Maximum memory that the container can use
      restartPolicy: Always
